[package]
name = "tack"
version = "0.1.0"
edition = "2021"
default-run = "tack"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
path-slash = "0.2.0"

[[bin]]
name = "tests"